### ISSUE TITLE
community_functions_NAs

### ISSUE THREAD

**Issue by itcarroll** [mavolio/codyn#11]
community_structure:

- [x] add examples
- [x] add description
- [x] update metrics specification (see issues specific to this)

community_diversity:

- [x] add examples
- [x] add description
- [x] update metrics specification (see issues specific to this)

**Comment by mavolio** [comment]
Should also stop of there are NAs in the abundance as these will be calculated.

**Comment by mavolio** [comment]
Evar is not working on all but 1 codyn dataset.

**Comment by mavolio** [comment]
do a check that abundance var does not contain NA's and give a clear error it is does for community structure and community diversity. - Maybe also do this for community RAC functions

**Comment by mavolio** [comment]
I tried adding a line of code 
  # check no NAs in abundance column
  if(any(is.na(df[[abundance.var]]))) stop("Abundance values are missing")

It isn't working. i do not know why.

**Comment by itcarroll** [comment]
You mean the line

    if(any(is.na(df[[abundance.var]]))) stop("Abundance values are missing")

in "community_structure"?

I tried with one NA in pplots$relative_cover in plot 6 and it stopped with that error. How is it not working for you?

**Comment by mavolio** [comment]
Yeah, I made a dummy dataset with NA and it gave me an error but not the
error I wanted. I can check again.

**Comment by mavolio** [comment]
It is working for me too now. I am closing this thread.
