### ISSUE TITLE
problem with large datasets in merge

### ISSUE THREAD

**Issue by mavolio** [mavolio/codyn#16]
When we run RAC-change for coydn dataset with replicate as an unique identifier something doesn't work.

Need to test for other multivariate change, and curve change too. 

Since it doesn't work of RAC change it won't for abundance change

**Comment by mavolio** [comment]
error with multivariate_change: Error in rowSums(x, na.rm = TRUE) : 'x' must be numeric 

This happens after vegdist

**Comment by mavolio** [comment]
Cannot work for multivariate chagne

**Comment by mavolio** [comment]
Add in to description that can do with multiple datasets by creating a making plot_id incorporate experiment information.

**Comment by itcarroll** [comment]
Try RAC_change with the big honker now.

**Comment by itcarroll** [comment]
The following ran with no errors in about 13 minutes on rstudio.sesync.org
```
out <- RAC_change(codyndat_clean, time.var = "experiment_year",
           species.var = "species",
           abundance.var = "abundance", replicate.var = "id")
```
There were 15529 rows in out.

I think we can close this issue?

**Comment by mavolio** [comment]
I agree, close it :)
