### ISSUE TITLE
abundance_difference

### ISSUE THREAD

**Issue by itcarroll** [mavolio/codyn#2]
- [x] need to add a description for the function
- [x] check to make sure the columns returned are correct
- [x] need to find and fix the section that assigns abund_diff instead of abundance.var_diff
- [x] need to add an example to the documentation
- [x] add documentation to the private functions
- [x] make the description of the abund_diff column more specific 
- [x] add details to the documentation if apppropriate

**Comment by itcarroll** [comment]
@mavolio I'm gonna wait on cleaning up the nested ifs in this function until it has an example that I can validate against.

**Comment by mavolio** [comment]
@itcarroll are you working on these this afternoon? I can quickly add some examples.

**Comment by itcarroll** [comment]
that would be great, thanks.

**Comment by mavolio** [comment]
get warning in the transpose. not sure why wiht the pplots data and time.

**Comment by mavolio** [comment]
warning
In reshapeWide(data, idvar = idvar, timevar = timevar,  ... :
  multiple rows match for species=senecio plattensis: first taken

**Comment by mavolio** [comment]
solved, my bad.

**Comment by mavolio** [comment]
@itcarroll added examples for curve, RAC, and abundance difference

**Comment by itcarroll** [comment]
In some of the examples, it shows `replicate.var = 'replicate'`. I'm changing that to `replicate.var = 'plots'` unless you say otherwise.

I'd also like to use TRUE and FALSE for pool, rather than "yes" and "no". Okay?

**Comment by mavolio** [comment]
Yes and sounds good.

If you have time, can you also look at what I address to structure and
diversity? I am not sure my na check fails.

**Comment by itcarroll** [comment]
For consistency with dropping the abundance.var on the output of the community_diversity and community_structure functions, I'm replacing abund_diff with "difference" (not abundance.var.diff).

That and lots of cleaning in 734c16d544d1df6e2116adc43cd4f232be282ced.
