### ISSUE TITLE
Output for community_structure diversity is ugly

### ISSUE THREAD

**Issue by mavolio** [mavolio/codyn#20]
The output columns for richness/evenness and diversity are now the abundnace.var.metic

I think this is too much and the columns should simply be called richness, whatever evenness metric was used and whatever diversity metric was used. 

When was this changed and why, and can we change it back?

**Comment by itcarroll** [comment]
i did that in 97780f762fdbb086cc3e207f91366257885a3c5d, and can change it back.

it happened automatically with the tidying i did on community_structure, and i thought it made sense so i left it.
