### ISSUE TITLE
Clean up code

### ISSUE THREAD

**Issue by mavolio** [mavolio/codyn#23]
Clean up, remove redundancies.

-  [x] community_diversity
- [x] community_structure
- [x] abundance_change
- [x] RAC_change
- [x] curve_change
- [x] multivariate_change
- [x] abundance_difference
- [x] RAC_difference
- [x] curve_difference
- [x] multivariate_difference

NON exported fucntions
- [x] add_ranks_replicate
- [x] add_ranks_time
- [x] pool_replicates
- [x] utilities functions

**Comment by mavolio** [comment]
I don't get how abundance change is calculated now.

**Comment by mavolio** [comment]
problems with curve difference:

null split var is not a good argument for split
also, not sure why pool is not working, i suspect there is nothing to compare in the curve-diff function due to a bad split somehow.

**Comment by mavolio** [comment]
make.row.names = FALSE for the change functions.

**Comment by mavolio** [comment]
figure out splitvars with only one thing to split by. don't need the ##

**Comment by itcarroll** [comment]
Need to revisit the *_change functions and the use of ## in time.x time.y merge.
Closing here though, because it will be taken care of when dealing with #16.
