### ISSUE TITLE
Test 2 year datasets

### ISSUE THREAD

**Issue by mavolio** [mavolio/codyn#33]
- [x] RAC_change
- [x] RAC_difference
- [x] abundance_change
- [x] abundance_difference
- [x] curve_change
- [x] curve_difference
- [x] multivariate_change
- [x] multivariate_difference

**Comment by itcarroll** [comment]
multivariate_x both give same error:
```
Error in data.frame(time1 = timestep[1:length(timestep) - 1], time2 = timestep[2:length(timestep)],  : 
  arguments imply differing number of rows: 1, 0
```

curve_difference_test is giving a different error, unrelated to number of years
```
 Error in if (is.unsorted(x)) stop("stepfun: 'x' must be ordered increasingly") : 
  missing value where TRUE/FALSE needed
```
