### ISSUE TITLE
confirm output columns are the same datatype as input

### ISSUE THREAD

**Issue by mavolio** [mavolio/codyn#36]
test this after curve_diff fixed.

Also this should affect the mapply with "<-["

**Comment by itcarroll** [comment]
Keeping open, need to revisit the outputs. Currently any ancillary data (that does not conflict with splits or merges, e.g. a year column in a data set with only one year) is dropped in the output_ordering code. I think its a good idea to not throw away users data when it doesn't interfere. If agreed, easy to change.

**Comment by itcarroll** [comment]
oops

**Comment by mavolio** [comment]
the output for time is different for the multivariate functions. I am not sure if there is a way around this.

**Comment by mavolio** [comment]
Hey Ian, can you look into the output columns for multivariate_* I know they are different. On line 52 in *change I have to have df[[treatment.var]]<-as.character(df[[treatment.var]]) or else it does not work if you subset a large dataset.

**Comment by mavolio** [comment]
multivariate_differene - not sure where or how, but time.var was output as a list obviously not ideal,

**Comment by itcarroll** [comment]
The root of this problem, and probably #51 too, is that transpose_community casts the time.var to character. Obv not going to mess with Lauren's functions. Considering alternatives ...

**Comment by mavolio** [comment]
Look into what I used to do with the reshape function. This is an
alternative but might also be bad.

**Comment by itcarroll** [comment]
Used reshape rather than transpose_community. Column type for time.var now preserved.

The output of multivariate_difference has an absolute difference and an additional column with the "larger" treatment. This is unlike multivariate_change ... which may be on purpose?

**Comment by mavolio** [comment]
Yes, mult_difference is the only function with that extra column. But now, when I was running with the simualted dataset and mult_diff was giving me time as a list. not a column.  Have you pushed these new functions? I can try again.

**Comment by itcarroll** [comment]
I did push. Did you rebuild?

--
Ian Carroll | carroll.ian@gmail.com | 805-291-7933

**Comment by mavolio** [comment]
I have but yet. I will try to afternoon.

**Comment by mavolio** [comment]
I think this is good. Should we close the issue?

**Comment by itcarroll** [comment]
Closing. I'm also on Skype if you want to check in anytime today. Can be online tomorrow afternoon too.
