### ISSUE TITLE
re-test with corre codyn

### ISSUE THREAD

**Issue by mavolio** [mavolio/codyn#37]
CORRE
- [x] abundance_change
- [x] RAC_change
- [x] curve_change
- [x] multivariate_change
get error with CORRE dataset only: Error in `colnames<-`(`*tmp*`, value = "time_forfixxyz") : 
  'names' attribute [1] must be the same length as the vector [0] 
- [x] abundance_difference
- [x] RAC_difference
- [x] curve_difference
- [x] multivariate_difference

CODYN
-  [x] community_diversity
- [x] community_structure
- [x] abundance_change
- [x] RAC_change
- [x] curve_change
- [x] multivariate_change

**Comment by itcarroll** [comment]
You can start testing, but not curve_difference yet.

I think something is wrong with abundance_difference: having to do with when zeros need to be added. Since I'm skeptical about that, my work is on branch RACs_cleaner but has everything from RACs at commit 06dcc09ff26caf7b6e99d707bc93a8e96f9a59e4 merged in.

**Comment by itcarroll** [comment]
Here's my general question about filling with zeros (example follows): should we only add zeros for species that are involved in a comparison (e.g. where abundance.var2 would be NA if not filled), or should it be filled based on the species pool that we get from merging across replicate.var or time.var?

For example:
```
data(pplots)
df <- subset(pplots, year == 2002 & block < 3, & species %in% c('dalea purpurea', 'carex meadii'))
df
```
```
     treatment plot block year        species relative_cover
17        N1P0   25     1 2002   carex meadii    0.031847134
72        N1P0   27     2 2002   carex meadii    0.020134228
1683      N2P0   29     1 2002   carex meadii    0.007827789
1690      N2P0   29     1 2002 dalea purpurea    0.001956947
1771      N2P0   32     2 2002   carex meadii    0.020278834
2926      N2P3   13     1 2002   carex meadii    0.010121457
3034      N2P3   21     2 2002   carex meadii    0.028708134
```
has a species that only shows up in one plot. Should the result of abundance_difference assume dalea purpurea is zero in all other plots:
```
   block plot plot2 treatment treatment2        species   difference
1      1   25    29      N1P0       N2P0   carex meadii  0.024019345
2      1   25    29      N1P0       N2P0 dalea purpurea -0.001956947
3      2   27    32      N1P0       N2P0   carex meadii -0.000144606
4      2   27    32      N1P0       N2P0 dalea purpurea  0.000000000
5      1   25    13      N1P0       N2P3   carex meadii  0.021725677
6      1   25    13      N1P0       N2P3 dalea purpurea  0.000000000
7      2   27    21      N1P0       N2P3   carex meadii -0.008573906
8      2   27    21      N1P0       N2P3 dalea purpurea  0.000000000
9      1   29    13      N2P0       N2P3   carex meadii -0.002293668
10     1   29    13      N2P0       N2P3 dalea purpurea  0.001956947
11     2   32    21      N2P0       N2P3   carex meadii -0.008429300
12     2   32    21      N2P0       N2P3 dalea purpurea  0.000000000
```
or that dalea purpurea is zero only in comparisons involving plot 29:
```
   block plot plot2 treatment treatment2        species   difference
1      1   25    29      N1P0       N2P0   carex meadii  0.024019345
2      1   25    29      N1P0       N2P0 dalea purpurea -0.001956947
3      2   27    32      N1P0       N2P0   carex meadii -0.000144606
5      1   25    13      N1P0       N2P3   carex meadii  0.021725677
7      2   27    21      N1P0       N2P3   carex meadii -0.008573906
9      1   29    13      N2P0       N2P3   carex meadii -0.002293668
10     1   29    13      N2P0       N2P3 dalea purpurea  0.001956947
11     2   32    21      N2P0       N2P3   carex meadii -0.008429300
```
In this case, you just filter out the rows with zero difference, but there could be cases where present species do not change in abundance.

**Comment by mavolio** [comment]
okay. I think you are doing this to get around the transpose? If a species is not in the comparison at either time points it does not matter and we want to drop those. However, I can imagine a situation where a species is present and its abundance has not changed, and we would want to include those. SO just deleting difference zeros will not work.

**Comment by mavolio** [comment]
Also, this makes it seem like fill_zeros is not fixed yet. Should I start running the tests or still hold off? I can work on this tonight after Leyla goes to bed, so I won't start until ~730. Just let me know when it is good to go. If you can more questions let me know.

**Comment by itcarroll** [comment]
fill_zeros is working, but it's currently keeping the zeros that the old fill_zeros_rep (which used reshape) also kept ... if the old examples I'm comparing against are old enough.

the only thing you shouldn't test yet is curve_difference. i'll have to finish that up tomorrow.

**Comment by itcarroll** [comment]
... and test on the RACs_cleaner branch.

**Comment by mavolio** [comment]
RAC_change takes over 20 minutes to run on the codyn dataset.

running it all as one big dataset, not looping is taking over 30 minutes.

**Comment by itcarroll** [comment]
I believe RAC_change, RAC_difference, abundance_change, and abundance_difference should all be back up to speed now. I implemented a new split_apply_combine utility function (with help from stackoverflow) and realized that splitting on species.var (which I had introduced) was unnecessary in *_change functions.

curve_* and multivariate_* could be condensed/cleaned more, but it's not essential -- they're legible. But if they're too slow, I could incorporate the new split_apply_combine function there too.

Please re-commence your testing/checking off satisfactory performance.

**Comment by itcarroll** [comment]
for loop through codyndat_clean subsets with RAC_change took rstudio.sesync.org about 12 minutes...

**Comment by mavolio** [comment]
This sounds great. I will start working on this again tomorrow. I think 12 minutes is slow, but these are large datasets. It should be very reasonable with smaller datasets. I will keep track of how long it takes for all permutation and note if I think curve_* and multivariate_* need to be cleaned to improve speed. My hope is that it is not going to be a problem and we can keep the subpar code as is and get this done. If it upsets you that some of the this code is subpar and you want to clean it, have at it.

**Comment by itcarroll** [comment]
I can live with it.

Will only touch it after/if Lauren replies about the time.var2 vs. time_pair question, to make everything consistent with what she dictates.

**Comment by mavolio** [comment]
Okay.  Tested all functions on both datasets.

First the good news:
community_structure and diversity work great and fast.

Bad news:
abundance_change and multivariate_change with CoDYN does not work, but both worked with codyn. Is this a PC - Mac thing? I am going to try on my mac now the CORRE datasets.

curve change gives a warning now as does curve_difference.

RAC difference takes 15 minutes but abundance difference only 4. Why such a big difference? I am attaching a spreadsheet of errors and time for each analysis

[Testing functions.xlsx](https://github.com/mavolio/codyn/files/1798217/Testing.functions.xlsx)

**Comment by itcarroll** [comment]
more likely a version difference than Mac vs. PC. does sessionInfo() show same R and package versions?

**Comment by itcarroll** [comment]
oh wait, you mean CORRE on one machine and codyn on the other (as in spreadsheet). i guess not quite handling all the edge cases with CORRE ...

**Comment by mavolio** [comment]
I am not near my PC so I can't check this. I am running them on the mac now, and RAC_change is taking much longer. AND yes, this was a typo - corre is the first one.

**Comment by mavolio** [comment]
Okay. somethings are different on my mac. See attached file. RAC difference is still taking a very long time. I stoppped the run after 40 minutes and for pplots alone it took 52 seconds for a single dataset. In contrast abundance_difference only took 6 minutes. one difference is that abundance doesn't rank, but do you think that step is taking so much longer?

[Testing functions.xlsx](https://github.com/mavolio/codyn/files/1799543/Testing.functions.xlsx)


If you want to try yourself. It is the 'testing with corre data' and 'testing with codyn' files in the RACs repository.

**Comment by mavolio** [comment]
All testing worked on codyn and corre datasets
