### ISSUE TITLE
complete pplots dataset documentation

### ISSUE THREAD

**Issue by itcarroll** [mavolio/codyn#38]
see content of 179ffca

**Comment by mavolio** [comment]
I am not sure what else is needed here. Is there an example somewhere?  and where is this documentation file?

**Comment by itcarroll** [comment]
There are examples in [R/codyn-package.R](https://github.com/mavolio/codyn/blob/RACs/R/codyn-package.R) for the other datasets in the package. Looks like a reference for the dataset and field descriptions are critical.
