### ISSUE TITLE
abundance_*

### ISSUE THREAD

**Issue by mavolio** [mavolio/codyn#39]
there is no need to rank.

**Comment by itcarroll** [comment]
makes sense. just delete that chunk from each one and make sure the right var (allsp?) gets passed on.

pool replicates will still rank ... oh, well?

**Comment by mavolio** [comment]
Sure, I will delete it and i think no harm no foul with pool replicates, right?

**Comment by mavolio** [comment]
Okay. somethings are different on my mac. See attached file. RAC difference is still taking a very long time. it is 52 seconds for a single dataset. 
[Testing functions.xlsx](https://github.com/mavolio/codyn/files/1798440/Testing.functions.xlsx)
