### ISSUE TITLE
multiple warnings, errors and speed probs

### ISSUE THREAD

**Issue by itcarroll** [mavolio/codyn#42]
- [x] curve_change and curve_difference warning on CORRE and CoDyn data (`In max(x) : no non-missing arguments to max; returning -Inf`)
- [x] RAC_difference needs speedup that abundance_difference got
- [x] multivariate change error on CORRE and CoDyn data (`'names' attribute [1] must be the same length as the vector [0]`)
- [x] abundance_difference needs to drop comparisons with zero species in both columns reliably, only appears to do it correctly without time.var

**Comment by itcarroll** [comment]
@mavolio Can you confirm that abundance_difference now seems to be doing what we want with missing species? Should be able to update it's tests. Then I'll patch other functions.

- [x] apply fix for missing species globally

**Comment by mavolio** [comment]
Yes, this works now. I will update the test

**Comment by mavolio** [comment]
It is not longer giving an error for species names being missing. I think we put this error in for fill_zeros?

**Comment by mavolio** [comment]
the curve_difference error only returns when using the pooling option, and it still give the correct result. but clearly getting a warning is not ideal.

**Comment by itcarroll** [comment]
I applied the hoped for speedups to RAC_difference, but profiling shows it is actually the SERSp function that's taking the bulk of time.

**Comment by mavolio** [comment]
Did you push the change? I can test on my computer? Also, do you have a moment to discuss the new dissim functions?

**Comment by itcarroll** [comment]
Oops. I meant to move the "species names missing" warning rather than delete it. It can go at the top level along with checking for NAs in the abundance, can't it? fill zeros now gets applied after splitting, so it shouldn't be in there.

**Comment by mavolio** [comment]
yes. it can go there.

**Comment by itcarroll** [comment]
can be on skype, briefly.

**Comment by itcarroll** [comment]
Originally four issues addressed. On to propagating the `fill_species` approach to handling missing species (see abundance_difference).

**Comment by itcarroll** [comment]
have fill_zeros for cases when pooling, and fill_species when not pooling. in the latter case, NAs are converted to zeros when only one NA remains in the row, otherwise the row is dropped.
