### ISSUE TITLE
dissimilarity_change - only want consecutive time pairings....hm....

### ISSUE THREAD

**Issue by mavolio** [mavolio/codyn#43]
not sure how to do this. will start thinking about it now

**Comment by itcarroll** [comment]
can you do it like in RAC_change line 82-89.

**Comment by mavolio** [comment]
What does this do? I have a table of three columns year, year2, and BC_between_change.

It is difficult for me to read lines 82-89.

**Comment by mavolio** [comment]
This is fixed!
