### ISSUE TITLE
make 1 multivariate function

### ISSUE THREAD

**Issue by mavolio** [mavolio/codyn#45]
make 1 multivariate function where you specify how compositional change/differences should be calculated - either with centroid distances or with bray-curtis distances.

Dispersion will always be calculated with centroids.

**Comment by mavolio** [comment]
@itcarroll Hey, I have combined dissimilarity_change and centriod_change to be one function called multivariate_change. This only calculated dispersion one way, but you specify how you want to measure composition change (based on centroids or ave bc dissimilarity). I *thought* i coped what you did for the community_* functions where you specify a metric, but this is not working for me and I am not now sure why. I get the error: Error in get(metric) : object 'centroid_distance' not found. This is the metric I put into the function. Can you look at this when  you have a chance?

**Comment by itcarroll** [comment]
Resolved. The `get` function takes a string and tries to find a function with the same name ... we didn't need that in this case.

The centroid_distance section needs attention still, which I assume you know. Starting with defining `timestep`.
