### ISSUE TITLE
centroid_change and x must be numeric

### ISSUE THREAD

**Issue by mavolio** [mavolio/codyn#51]
MSH_centroid_output<-centroid_change(df=codyndat_clean, time.var="experiment_year",replicate.var="id", species.var="species", abundance.var="abundance")
Error in rowSums(x, na.rm = TRUE) : 'x' must be numeric

**Comment by mavolio** [comment]
This is because Cynthia is trying to feed in an unique id for each plot and you need replicates for this calculation. I need to make a good and clear error about this.

**Comment by mavolio** [comment]
Ian. I am stumped. I thought the error was because Cynthia did not have replicate plots. but what is throwing the error is not what I had thought. In line 101 of *change function I drop the id column. If id looks like this: "1981##tephra_SR_999::99"t he column is not dropped, but if it looks like this: "1980##1" the column is dropped. The code to drop the column is  species3 <- subset(species2, select = -id). Why is this happening?

I want to create an error about not having replicates but I cannot think of a creative way to do this. In the Cynthia's example, she has a large dataset that instead of looping, she has added site information to replicate, and then fed that through the functions. for all of the other functions this works, because you do not need replicates. For multivariate_* you do need replicates. So by here plot_id also having site info there is only 1 plot and year combination, anyway. I think this did work in the past there is just no dispersion (all values would be zero), I would like to give a warning message about this, in addition to fixing the error above.

attached is the file she was working with.
[msh.txt](https://github.com/mavolio/codyn/files/1868228/msh.txt)

**Comment by mavolio** [comment]
msh<-read.csv("msh.csv")

output<-multivariate_change(msh, time.var = "experiemnt_year", abundance.var = "abundance", species.var = "species", replicate.var = "id")

now i am getting a different error:

Error in table(xx[[species.var]], xx[[time.var]]) : 
  all arguments must have the same length

**Comment by itcarroll** [comment]
No more 'id' column to drop, and the following code worked for me (a bit slowly, but I guess there's a lot of rows).

```
msh <- read.table("msh.txt", header = TRUE)

output <- multivariate_change(msh,
  time.var = "experiment_year", abundance.var = "abundance",
  species.var = "species", replicate.var = "id")
``` 

~If I understand how this data is arranged, you want an error to be generated because there is only one level of replicate.var over time, right? Or do you think it should check each time, that there is more than one replicate?~

No, that's not it. This function is unlike the others because in a way it always pools replicates. I think the fact that it works on other functions to "abuse" the replicate.var (by making plots from independent studies "replicates") doesn't mean you have to have this one generate an error. They'll see the output is not what they were expecting.

**Comment by mavolio** [comment]
Do you have time to discuss this? I have some time in the afternoon and tomorrow. it might also be nice to check in on overall progress.

**Comment by mavolio** [comment]
have a message about the number of replicates.

message for multivariate_change: composition and dispersion change are calculated based on X replicates in each year.

message for multivariate_difference: composition and dispersion differences are calculated based on X replicates in each treatment.

or something like that.

**Comment by itcarroll** [comment]
Did you want a message about replicates for each time.var / treatment.var? I guessed you did, since I suppose it's possible to change. Will you confirm or deny?

**Comment by itcarroll** [comment]
I pushed the change, so you can see how it behaves currently.

**Comment by mavolio** [comment]
add details to the example
