### ISSUE TITLE
not selecting columns in the beginning of fuctions

### ISSUE THREAD

**Issue by mavolio** [mavolio/codyn#52]
Hey Ian,

I know we see differently on this. You think we should keep extra columns and I think they should be dropped. I am going to give 2 reasons why they should be dropped. 

1) in RAC change, there is a merge and extra columns are not merged corrected and gives a warning
2) for all the functions we specify the order of the output so extra columns are not output anyway.

What do you think? If you agree, I am going to add back in to the start of the function to select the necessary columns only.

**Comment by itcarroll** [comment]
I agree. Fix with 800279f7837a0842233ebee800572bc8c26c969c.
