### ISSUE TITLE
compare old and new curve change

### ISSUE THREAD

**Issue by mavolio** [mavolio/codyn#53]

**Comment by mavolio** [comment]
The output has changed from what was run in January 2018 and in September 2017. I am not sure why. 

AND_control_0 1990-1992 average used to be 0.128 is now 0.220. It has not changed for the simulated community. Nothing needs to be added for curve change so I wonder what is causing this.

**Comment by mavolio** [comment]
I wonder if this has to do with some plots not being measured all years and some messiness there.

**Comment by itcarroll** [comment]
Will dig into this and finish off the warning message this afternoon.

**Comment by mavolio** [comment]
Sounds good. Once it is all done Let's move this over to the main codyn
branch before everyone starts testing it next week. I am not 100% sure how
to do that, but i am sure you and Matt can teach me.

Meghan

**Comment by itcarroll** [comment]
So I went back to the version of curve_change that was first copied from your RACs repository on Jan 25, and the mean value for experiment_year 1990-1992 was 0.2202039, as it is now. Digging deeper will be harder, since I'd have to go into the non-package version of the functions.

Very well could have to do with irregular sampling for codyndat set site_project_comm == AND_control_0:

```
> table(subset$experiment_year, subset$plot_id)
        1 10 11 12 13 14 15 16 17 18 19  2 20 21 22 23 24 25  3  4  5  6  7  8  9
  1990 24 24  0  0 24  0 24 24 24 24  0 24 24 24 24 24 24 24  0 24 24 24 24 24 24
  1992  0 24  0  0 24  0  0 24  0 24 24 24 24 24  0  0 24  0  0 24  0 24 24 24  0
  1993 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24
```

Trust it or keep digging?

**Comment by mavolio** [comment]
hmm....do you

**Comment by itcarroll** [comment]
I regenerated the 0.128 value for AND_Control_0 using the code in "mavolio/RACs/Old code to make functions/Measurements and Analyses_SERGL.R" beginning at line 490.

The curve_change values calculated for each plot are identical, but there is a section of old code (lines 534-551) with comment "dropping plots with only 1 species in any of the two years" that eliminates several plots, changing the average. This section does not seem to be reflected in the codyn/curve_change function.

What's that about?

**Comment by mavolio** [comment]
AHA!

When you first wrote this code (before it was a function), plots that were
not measured consecutive years were dropped. I think you did this because
it did not work if plots had only 1 species (I am not 100% sure). However,
the code still works if plots only have one species, so I dropped this.

Thus, I think the current result is the correct result!! and we are done
with this. What do you think?

**Comment by itcarroll** [comment]
Current results are correct.
