### ISSUE TITLE
rac change not working on dataframe

### ISSUE THREAD

**Issue by mavolio** [mavolio/codyn#54]
this is the error. i have no idea what is causing this. I have run this code in the past and it has worked.

this is because it is remembering all the thigns from teh larger dataframe from where it was subset from. I thought we fixed all of these? why does it work sometimes but not all the time.

Error in FUN(X[[i]], ...) : Input df has not been correctly split

**Comment by mavolio** [comment]
dat<-read.csv("~/Dropbox/converge_diverge/datasets/Longform/SpeciesRelativeAbundance_Oct2017.csv")

dat<-read.csv("C:\\Users\\megha\\Dropbox\\converge_diverge\\datasets\\Longform\\SpeciesRelativeAbundance_Oct2017.csv")
traits<-read.csv("C:\\Users\\megha\\Dropbox\\pplots\\site_review_2017\\traits_final.csv")

##pplots
pplots<-dat%>%
  filter(project_name=="pplots",calendar_year==2002|calendar_year==2011, treatment=="N1P0"|treatment=="N2P3"|treatment=="N2P0")%>%
  tbl_df()%>%
  group_by(calendar_year, plot_id)%>%
  mutate(rank=rank(-relcov, ties.method="average"),
         treatment=factor(treatment, levels=c("N1P0","N2P0", "N2P3")))###need to do this b/c otherwise R will remember every treatment

**Comment by mavolio** [comment]
pplots<-dat%>%
  filter(project_name=="pplots",calendar_year==2002|calendar_year==2011, treatment=="N1P0"|treatment=="N2P3"|treatment=="N2P0")%>%
  tbl_df()%>%
  group_by(calendar_year, plot_id)%>%
    mutate(rank=rank(-relcov, ties.method="average"))%>%
  ungroup()%>%
  mutate(treatment=factor(treatment, levels=c("N1P0","N2P0", "N2P3")),
         genus_species=as.character(genus_species),
         plot_id = as.character(plot_id))###need to do this b/c otherwise R will remember every treatment

It is not what I thought is causing it. Getting the pplots dataset to no longer "remember" attributes of the other dataset does not solve the problem.

**Comment by mavolio** [comment]
This is still a problem. Not sure what is causing it.

**Comment by mavolio** [comment]
We should make the error message clearer:
Input df has not been correctly split.

maybe something like: the number of X does not match what is expected. 

I am still unclear on what is generating the error...but once I do hopefully I can have a better suggestion

**Comment by itcarroll** [comment]
RAC_change works for me on pplots subset form dat IF I take out the 'X' column R introduces when reading from the table. X was no doubt written by R as row.name.

Confirms that the problem will be resolved by removing extraneous columns ... which I'm about to do.

**Comment by itcarroll** [comment]
See #52 . Also fixed with 800279f7837a0842233ebee800572bc8c26c969c.
