### ISSUE TITLE
NCEAS/codyn RAC_functions branch

### ISSUE THREAD

**Issue by itcarroll** [mavolio/codyn#55]
Some commits by mbjones that may still be relevant and should be incorporated into PR. I cannot recall the history of this branch in NCEAS/codyn, or why those commits are not in the history of mavolio/codyn. Beyond these few commits though, I don't think there's anything lost.

- [x] https://github.com/NCEAS/codyn/commit/dbb8c8eb5a4d802117c1099961537f7b63d396c4
- [x] https://github.com/NCEAS/codyn/commit/f5b3f3c328924fa0eb1c67ae0bbfceeb3570cb15
- [ ] https://github.com/NCEAS/codyn/commit/ab7210c091cfb6f4476e6017e7833d57cef74738

**Comment by mavolio** [comment]
I don't know anything about these. Maybe Matt knows more.

**Comment by itcarroll** [comment]
Got the important ones. Gonna ignore that last one, which should be in the global .gitignore of whoever uses Visual Studio and not in the repo.
